#!/usr/bin/env python

import os
import sys
from subprocess import Popen, PIPE

def send(s):
	p = Popen([ "y9p", "write", "prop" ], shell=False, stdin=PIPE)
	p.communicate(s)

arg = sys.argv[1] if len(sys.argv) > 1 else "switch"

if arg == "help" or arg == "-h":
	print "Changes the font of the current frame:"
	print "\tswitch\t\tToggles between main and alt font"
	print "\tmain\t\tSwitches to main (usually proportional) font"
	print "\talt\t\t\tSwitches to alt (usually monospaced) font"
	print "\t+\t\t\tIncreses font size"
	print "\t-\t\t\tDecreases font size"
else:
	send("font=" + arg)
