#!/usr/bin/env python

import os
import sys

arg = sys.argv[1] if len(sys.argv) > 1 else "switch"

if os.environ["bd"] != "":
	fh = file(os.environ["bd"] + "/prop", "a")
	fh.write("font=" + arg)
	fh.close()
elif os.environ["yd"] != "":
	fh = file(os.environ["yd"] + "/prop", "a")
	fh.write("font=" + arg)
	fh.close()

