#!/usr/bin/env python

import os
import sys
from subprocess import Popen, PIPE

def send(s):
	p = Popen([ "y9p", "write", "prop" ], shell=False, stdin=PIPE)
	p.communicate(s)

arg = sys.argv[1] if len(sys.argv) > 1 else "switch"

send("font=" + arg)
