#!/bin/bash

if [ "x$yp9" != "x" ]; then
	export bi=`y9p find +Grep`
	echo -n , | y9p write buf/addr
	echo -ne '\0000' | y9p write buf/data
	echo $ grep -in $1 | y9p write buf/body
	echo show | y9p write buf/ctl
	LookFile -list | xargs grep -in $1 2>&1 | y9p write buf/body
	exit 0
else
	echo searching $1
	LookFile -list | xargs grep -in $1
fi
