#!/bin/bash

if [ "x$yp9" != "x" ]; then
	export bi=`y9p find +Grep`
	echo -n , | y9p write buf/addr
	echo -ne '\0000' | y9p write buf/data
	echo $ grep -in $1 | y9p write buf/body
	echo show | y9p write buf/ctl
	find ./  -path "*/vendor/*" -prune -or -name '*.c' -or -name '*.cc' -or -name '*.cpp' -or -name '*.h' -or -name '*.py' -or -name '*.txt' -or -name '*.pl' -or -name '*.tcl' -or -name '*.java' -or -name '*.js' -or -name '*.html' -or -name '*.go' -or -name '*.clj' -or -name '*.jsp' | xargs grep -in $1 2>&1 | y9p write buf/body
	exit 0
else
	echo searching $1
	find ./ -path "*/vendor/*" -prune -or -name '*.c' -or -name '*.cc' -or -name '*.cpp' -or -name '*.h' -or -name '*.py' -or -name '*.txt' -or -name '*.pl' -or -name '*.tcl' -or -name '*.java' -or -name '*.js' -or -name '*.html' -or -name '*.go' -or -name '*.clj' -or -name '*.jsp' | xargs grep -in $1
fi
