#!/bin/bash

export bi=`y9p find +Grep`
echo -n , | y9p write buf/addr
echo -ne '\0000' | y9p write buf/data
echo -n gg | y9p write buf/tag
echo $ gg $1 | y9p write buf/body
global --result=grep $* | y9p write buf/body
