#!/usr/bin/env python

import sys
import os
import string
from subprocess import Popen, PIPE

def send(s):
	p = Popen([ "y9p", "write", "prop" ], shell=False, stdin=PIPE)
	p.communicate(s)

cmd = ""

if len(sys.argv) >= 2:
	cmd = sys.argv[1]

if cmd == "":
	p = Popen([ "y9p", "read", "prop" ], shell=False, stdout=PIPE)
	out, err = p.communicate()
	curval = "off"
	for line in out.split("\n"):
		if line.startswith('indent='):
			curval = line[len('indent='):]
			
	newval = "on" if curval != "on" else "off"
	send("indent=" + newval)
elif cmd == "on":
	send("indent=on")
elif cmd == "off":
	send("indent=off")
elif (len(cmd) > 0) and (cmd[0] == 't'):
	ic = '\t' * string.atoi(cmd[1:])
	send("indentchar=" + ic)
elif (len(cmd) > 0) and (cmd[0] == 's'):
	ic = ' ' * string.atoi(cmd[1:])
	send("indentchar=" + ic)
else:
	print "Wrong command argument to Indent"
