#!/usr/bin/env python

import os
import sys
from subprocess import Popen, PIPE

def send(s, dst):
	p = Popen([ "y9p", "write", dst ], shell=False, stdin=PIPE)
	p.communicate(s)

if sys.argv[1] == "help" or sys.argv[1] == "-h":
	print "Tab stops manipulation:"
	print "\tTab <width>"
	print "Sets the number of spaces that correspond to a tab"
else:
	send("tab=" + sys.argv[1], "prop")
