#!/usr/bin/env python

import sys
import os

#Grep index for one with the specified name
idxfd = open(os.environ["yd"] + "/index")
for x in idxfd:
	if x[len(x)-1] == '\n':
		x = x[:len(x)-1]
	filename = x[60:]
	if filename.endswith(sys.argv[1]):
		print os.environ["yd"] + "/" + str(int(x[:11])),
		idxfd.close()
		sys.exit(0)
idxfd.close()

# Create a new directory
fh = file(os.environ["yd"] + "/new/ctl")
c = fh.read()
fh.close()
bd = os.environ["yd"] + "/" + str(int(c[:11]))
fh = file(bd + "/ctl" , "a")
fh.write("name " + sys.argv[1])
fh.close()
print bd,



