#!/usr/bin/env python

import sys
import os

fh = file(os.environ["yd"] + "/new/ctl")
c = fh.read()
fh.close()
bd = os.environ["yd"] + "/" + str(int(c[:11]))
fh = file(bd + "/ctl" , "a")
fh.write("name " + sys.argv[1])
fh.close()
print bd,



